apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-deployment
  labels:
    app: yolo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
        - name: client-container
          image: rwambui/yolo-client:1.0.0
          ports:
            - containerPort: 3000
        - name: backend-container
          image: rwambui/yolo-backend:1.0.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: backend-volume
              mountPath: /data/db
      volumes:
        - name: backend-volume
          persistentVolumeClaim:
            claimName: mongodb-pvc



       