apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  selector:
    app: yolo-app
  ports:
    - name: client-port
      port: 3000
      targetPort: 3000
    - name: backend-port
      port: 5000
      targetPort: 5000
      nodePort: 31000
  type: LoadBalancer